"""Minecraft block -> Islands block mapping, shared by both converters."""

# Bulk terrain never carried over.
BULK = {
    "minecraft:stone", "minecraft:dirt", "minecraft:bedrock",
    "minecraft:andesite", "minecraft:diorite", "minecraft:granite",
    "minecraft:gravel", "minecraft:water", "minecraft:lava",
    "minecraft:coal_ore", "minecraft:iron_ore", "minecraft:gold_ore",
    "minecraft:diamond_ore", "minecraft:redstone_ore", "minecraft:lapis_ore",
    "minecraft:emerald_ore", "minecraft:infested_stone",
}

# Minecraft block -> Islands block. Chosen for closest colour/material; Islands
# has no wall/fence/pane/door/carpet primitives, so those become the nearest
# full block or slab.
MAP = {
    # stone and concrete
    "minecraft:smooth_stone": "stoneSmooth",
    "minecraft:stone_bricks": "stoneBrick",
    "minecraft:smooth_stone_slab": "stoneBrickSlab",
    "minecraft:stone_slab": "stoneBrickSlab",
    "minecraft:petrified_oak_slab": "oakSlab",
    "minecraft:cobblestone": "cobblestoneBlock",
    "minecraft:mossy_cobblestone": "mossyCobblestoneBlock",
    "minecraft:andesite_wall": "andesite",
    "minecraft:diorite_wall": "diorite",
    "minecraft:cobblestone_wall": "cobblestoneBlock",
    "minecraft:light_gray_concrete": "marbleSmooth",
    "minecraft:white_concrete": "whiteBlock",
    "minecraft:black_concrete": "blackBlock",
    "minecraft:gray_concrete": "slateSmooth",
    "minecraft:smooth_quartz": "marbleBlock",
    "minecraft:quartz_block": "marbleBlock",
    "minecraft:coal_block": "coalBlock",
    "minecraft:iron_block": "ironBlock",
    "minecraft:glowstone": "ledLight",
    "minecraft:sea_lantern": "ledLight",
    "minecraft:bricks": "brick",
    "minecraft:nether_bricks": "basaltBrick",
    "minecraft:nether_brick_stairs": "basaltBrickStair",
    "minecraft:nether_brick_slab": "basaltBrickSlab",
    "minecraft:nether_brick_fence": "basaltBrick",

    # sandstone
    "minecraft:smooth_sandstone": "sandstoneSmooth",
    "minecraft:smooth_sandstone_slab": "sandstoneSmoothSlab",
    "minecraft:smooth_sandstone_stairs": "stairSandstoneSmooth",
    "minecraft:sandstone": "sandstone",
    "minecraft:sandstone_wall": "sandstone",
    "minecraft:sandstone_slab": "sandstoneSlab",
    "minecraft:sandstone_stairs": "stairSandstone",
    "minecraft:chiseled_sandstone": "sandstoneBrick",
    "minecraft:cut_sandstone": "sandstoneBrick",
    "minecraft:red_sandstone": "sandstoneRed",

    # wood: spruce -> pine, dark oak -> hickory (closest tones Islands has)
    "minecraft:spruce_planks": "pinePlank",
    "minecraft:spruce_slab": "pineSlab",
    "minecraft:spruce_stairs": "stairPine",
    "minecraft:spruce_log": "woodPine",
    "minecraft:stripped_spruce_log": "woodPine",
    "minecraft:spruce_fence": "pinePlank",
    "minecraft:spruce_fence_gate": "pinePlank",
    "minecraft:spruce_door": "pinePlank",
    "minecraft:spruce_trapdoor": "pineSlab",
    "minecraft:spruce_pressure_plate": "pineSlab",
    "minecraft:spruce_sign": "pineSlab",
    "minecraft:spruce_wall_sign": "pineSlab",

    "minecraft:oak_planks": "woodPlank",
    "minecraft:oak_slab": "oakSlab",
    "minecraft:oak_stairs": "stairOak",
    "minecraft:oak_log": "wood",
    "minecraft:stripped_oak_log": "wood",
    "minecraft:oak_fence": "woodPlank",
    "minecraft:oak_fence_gate": "woodPlank",
    "minecraft:oak_door": "woodPlank",
    "minecraft:oak_trapdoor": "oakSlab",
    "minecraft:oak_pressure_plate": "oakSlab",
    "minecraft:oak_button": "oakSlab",
    "minecraft:oak_sign": "oakSlab",
    "minecraft:oak_wall_sign": "oakSlab",

    "minecraft:birch_planks": "birchPlank",
    "minecraft:birch_slab": "birchSlab",
    "minecraft:birch_stairs": "stairBirch",
    "minecraft:birch_log": "woodBirch",
    "minecraft:stripped_birch_log": "woodBirch",
    "minecraft:birch_fence": "birchPlank",
    "minecraft:birch_fence_gate": "birchPlank",
    "minecraft:birch_door": "birchPlank",
    "minecraft:birch_trapdoor": "birchSlab",
    "minecraft:birch_button": "birchSlab",

    "minecraft:dark_oak_planks": "hickoryPlank",
    "minecraft:dark_oak_slab": "hickorySlab",
    "minecraft:dark_oak_stairs": "stairHickory",
    "minecraft:dark_oak_log": "woodHickory",
    "minecraft:dark_oak_fence": "hickoryPlank",
    "minecraft:dark_oak_fence_gate": "hickoryPlank",
    "minecraft:dark_oak_door": "hickoryPlank",
    "minecraft:dark_oak_trapdoor": "hickorySlab",

    "minecraft:jungle_planks": "maplePlank",
    "minecraft:jungle_log": "woodMaple",
    "minecraft:acacia_planks": "maplePlank",
    "minecraft:acacia_log": "woodMaple",
    "minecraft:bookshelf": "hickoryPlank",
    "minecraft:crafting_table": "woodPlank",
    "minecraft:barrel": "pinePlank",
    "minecraft:chest": "woodPlank",
    "minecraft:trapped_chest": "woodPlank",
    "minecraft:ladder": "oakSlab",
    "minecraft:scaffolding": "bambooBlock",

    # leaves and plants
    "minecraft:oak_leaves": "leavesBlock",
    "minecraft:birch_leaves": "leavesBlock",
    "minecraft:spruce_leaves": "leavesBlock",
    "minecraft:jungle_leaves": "leavesMapleBlock",
    "minecraft:acacia_leaves": "leavesMapleBlock",
    "minecraft:dark_oak_leaves": "leavesBlock",
    "minecraft:vine": "leavesBlock",
    "minecraft:grass_block": "grass",
    "minecraft:grass_path": "grassDry",
    "minecraft:dirt_path": "grassDry",
    "minecraft:coarse_dirt": "mudBlock",
    "minecraft:podzol": "mudBlock",
    "minecraft:farmland": "mudBlock",
    "minecraft:hay_block": "haybaleBlock",
    "minecraft:pumpkin": "pumpkinHarvested",
    "minecraft:carved_pumpkin": "jackOLantern",
    "minecraft:jack_o_lantern": "jackOLantern",
    "minecraft:melon": "melonHarvested",
    "minecraft:mushroom_stem": "mushroomBlock",
    "minecraft:brown_mushroom_block": "mushroomBlock",
    "minecraft:red_mushroom_block": "mushroomBlock",
    "minecraft:cobweb": "woolWhite",

    # wool and carpet
    "minecraft:white_wool": "woolWhite",
    "minecraft:black_wool": "woolBlack",
    "minecraft:red_wool": "woolRed",
    "minecraft:blue_wool": "woolBlue",
    "minecraft:light_blue_wool": "woolCyan",
    "minecraft:cyan_wool": "woolCyan",
    "minecraft:green_wool": "woolDarkGreen",
    "minecraft:lime_wool": "woolLightGreen",
    "minecraft:yellow_wool": "woolYellow",
    "minecraft:orange_wool": "woolOrange",
    "minecraft:pink_wool": "woolPink",
    "minecraft:magenta_wool": "woolPink",
    "minecraft:purple_wool": "woolPurple",
    "minecraft:brown_wool": "clayOrange",
    "minecraft:gray_wool": "clayBlack",
    "minecraft:light_gray_wool": "clayWhite",

    "minecraft:white_carpet": "whiteSlab",
    "minecraft:black_carpet": "blackSlab",
    "minecraft:red_carpet": "redSlab",
    "minecraft:blue_carpet": "blueSlab",
    "minecraft:light_blue_carpet": "cyanSlab",
    "minecraft:cyan_carpet": "cyanSlab",
    "minecraft:green_carpet": "darkGreenSlab",
    "minecraft:lime_carpet": "lightGreenSlab",
    "minecraft:yellow_carpet": "yellowSlab",
    "minecraft:orange_carpet": "orangeSlab",
    "minecraft:pink_carpet": "pinkSlab",
    "minecraft:purple_carpet": "purpleSlab",
    "minecraft:gray_carpet": "blackSlab",
    "minecraft:light_gray_carpet": "whiteSlab",
    "minecraft:brown_carpet": "orangeSlab",

    # glass
    "minecraft:glass": "glassBlockChrome",
    "minecraft:glass_pane": "glassBlockChrome",
    "minecraft:white_stained_glass": "glassBlockChrome",
    "minecraft:white_stained_glass_pane": "glassBlockChrome",
    "minecraft:black_stained_glass": "glassBlockBlack",
    "minecraft:black_stained_glass_pane": "glassBlockBlack",
    "minecraft:blue_stained_glass_pane": "glassBlockBlue",
    "minecraft:red_stained_glass_pane": "glassBlockRed",
    "minecraft:green_stained_glass_pane": "glassBlockDarkGreen",
    "minecraft:lime_stained_glass_pane": "glassBlockLightGreen",
    "minecraft:yellow_stained_glass_pane": "glassBlockYellow",
    "minecraft:orange_stained_glass_pane": "glassBlockOrange",
    "minecraft:cyan_stained_glass_pane": "glassBlockCyan",
    "minecraft:pink_stained_glass_pane": "glassBlockPink",
    "minecraft:purple_stained_glass_pane": "glassBlockPurple",
    "minecraft:brown_stained_glass_pane": "glassBlockOrange",
    "minecraft:gray_stained_glass_pane": "glassBlockBlack",
    "minecraft:light_gray_stained_glass_pane": "glassBlockChrome",

    # lights and small props: nearest solid stand-in
    "minecraft:torch": "ledLight",
    "minecraft:wall_torch": "ledLight",
    "minecraft:lantern": "ledLight",
    "minecraft:soul_lantern": "ledLight",
    "minecraft:campfire": "magmaBlock",
    "minecraft:end_rod": "ledLight",
    "minecraft:iron_bars": "ironBlock",
    "minecraft:cauldron": "ironBlock",
    "minecraft:anvil": "ironBlock",
    "minecraft:furnace": "cobblestoneBlock",
    "minecraft:smoker": "pinePlank",
    "minecraft:blast_furnace": "ironBlock",
    "minecraft:stonecutter": "stoneSmooth",
    "minecraft:grindstone": "woodPlank",
    "minecraft:lectern": "woodPlank",
    "minecraft:composter": "woodPlank",
    "minecraft:bell": "goldBlock",
    "minecraft:player_head": "boneBlock",
    "minecraft:heavy_weighted_pressure_plate": "ironBlock",
    "minecraft:stone_button": "stoneSmooth",
    "minecraft:stone_pressure_plate": "stoneSmooth",
    "minecraft:flower_pot": "clayOrange",
    "minecraft:bed": "woolRed",
    "minecraft:white_bed": "woolWhite",
    "minecraft:red_bed": "woolRed",
    "minecraft:blue_bed": "woolBlue",
    "minecraft:green_bed": "woolDarkGreen",
    "minecraft:light_blue_wall_banner": "woolCyan",
    "minecraft:white_wall_banner": "woolWhite",
    "minecraft:item_frame": "woodPlank",
    "minecraft:painting": "woodPlank",

    # stragglers found on the first pass
    "minecraft:dark_oak_wall_sign": "hickorySlab",
    "minecraft:tripwire_hook": "oakSlab",
    "minecraft:spruce_button": "pineSlab",
    "minecraft:spruce_wood": "woodPine",
    "minecraft:oak_wood": "wood",
    "minecraft:birch_wood": "woodBirch",
    "minecraft:dark_oak_wood": "woodHickory",
    "minecraft:gold_block": "goldBlock",
    "minecraft:emerald_block": "amethystBlock",
    "minecraft:diamond_block": "diamondBlock",
    "minecraft:redstone_block": "redBlock",
    "minecraft:lapis_block": "blueBlock",
    "minecraft:smooth_quartz_slab": "marbleSlab",
    "minecraft:quartz_slab": "marbleSlab",
    "minecraft:jungle_door": "maplePlank",
    "minecraft:iron_door": "ironBlock",
    "minecraft:iron_trapdoor": "ironBlock",
    "minecraft:stone_stairs": "stairStoneBrick",
    "minecraft:repeating_command_block": "stoneSmooth",
    "minecraft:command_block": "stoneSmooth",
    "minecraft:lever": "oakSlab",
    "minecraft:brewing_stand": "ironBlock",
    "minecraft:enchanting_table": "voidStoneBlock",
    "minecraft:jukebox": "hickoryPlank",
    "minecraft:note_block": "woodPlank",
    "minecraft:beacon": "glassBlockChrome",

    # ── terracotta (1.13+) ────────────────────────────────────────────────
    "minecraft:terracotta": "clayOrange",
    "minecraft:white_terracotta": "clayWhite",
    "minecraft:black_terracotta": "clayBlack",
    "minecraft:gray_terracotta": "clayBlack",
    "minecraft:light_gray_terracotta": "clayWhite",
    "minecraft:red_terracotta": "clayRed",
    "minecraft:orange_terracotta": "clayOrange",
    "minecraft:yellow_terracotta": "clayYellow",
    "minecraft:lime_terracotta": "clayLightGreen",
    "minecraft:green_terracotta": "clayDarkGreen",
    "minecraft:cyan_terracotta": "clayCyan",
    "minecraft:light_blue_terracotta": "clayCyan",
    "minecraft:blue_terracotta": "clayBlue",
    "minecraft:purple_terracotta": "clayPurple",
    "minecraft:magenta_terracotta": "clayPink",
    "minecraft:pink_terracotta": "clayPink",
    "minecraft:brown_terracotta": "clayOrange",

    # ── concrete and concrete powder ──────────────────────────────────────
    "minecraft:red_concrete": "redBlock",
    "minecraft:orange_concrete": "orangeBlock",
    "minecraft:yellow_concrete": "yellowBlock",
    "minecraft:lime_concrete": "lightGreenBlock",
    "minecraft:green_concrete": "darkGreenBlock",
    "minecraft:cyan_concrete": "cyanBlock",
    "minecraft:light_blue_concrete": "cyanBlock",
    "minecraft:blue_concrete": "blueBlock",
    "minecraft:purple_concrete": "purpleBlock",
    "minecraft:magenta_concrete": "pinkBlock",
    "minecraft:pink_concrete": "pinkBlock",
    "minecraft:brown_concrete": "clayOrange",
    "minecraft:white_concrete_powder": "sand",
    "minecraft:light_gray_concrete_powder": "clayWhite",
    "minecraft:gray_concrete_powder": "clayBlack",
    "minecraft:brown_concrete_powder": "sand",
    "minecraft:black_concrete_powder": "clayBlack",
    "minecraft:red_concrete_powder": "clayRed",
    "minecraft:yellow_concrete_powder": "sand",

    # ── nether / 1.16 woods ───────────────────────────────────────────────
    "minecraft:warped_planks": "spiritPlank",
    "minecraft:warped_slab": "spiritSlab",
    "minecraft:warped_stairs": "stairSpirit",
    "minecraft:warped_fence": "spiritPlank",
    "minecraft:warped_fence_gate": "spiritPlank",
    "minecraft:warped_door": "spiritPlank",
    "minecraft:warped_trapdoor": "spiritSlab",
    "minecraft:warped_button": "spiritSlab",
    "minecraft:warped_stem": "woodSpirit",
    "minecraft:warped_hyphae": "woodSpirit",
    "minecraft:stripped_warped_stem": "woodSpirit",
    "minecraft:warped_wart_block": "glowingMushroomCyanBlock",
    "minecraft:crimson_planks": "cherryBlossomPlank",
    "minecraft:crimson_slab": "cherryBlossomSlab",
    "minecraft:crimson_stairs": "stairCherryBlossom",
    "minecraft:crimson_fence": "cherryBlossomPlank",
    "minecraft:crimson_fence_gate": "cherryBlossomPlank",
    "minecraft:crimson_door": "cherryBlossomPlank",
    "minecraft:crimson_trapdoor": "cherryBlossomSlab",
    "minecraft:crimson_button": "cherryBlossomSlab",
    "minecraft:crimson_stem": "woodCherryBlossom",
    "minecraft:crimson_hyphae": "woodCherryBlossom",
    "minecraft:stripped_crimson_stem": "woodCherryBlossom",
    "minecraft:nether_wart_block": "glowingMushroomPinkBlock",
    "minecraft:soul_soil": "mudBlock",
    "minecraft:soul_sand": "mudBlock",
    "minecraft:basalt": "basalt",
    "minecraft:polished_basalt": "basaltSmooth",
    "minecraft:smooth_basalt": "basaltSmooth",
    "minecraft:blackstone": "basalt",
    "minecraft:polished_blackstone": "basaltSmooth",
    "minecraft:polished_blackstone_bricks": "basaltBrick",
    "minecraft:polished_blackstone_stairs": "basaltBrickStair",
    "minecraft:polished_blackstone_slab": "basaltBrickSlab",
    "minecraft:polished_blackstone_button": "basaltSlab",
    "minecraft:polished_blackstone_wall": "basaltBrick",
    "minecraft:red_nether_bricks": "sandstoneRedBrick",
    "minecraft:red_nether_brick_wall": "sandstoneRedBrick",
    "minecraft:red_nether_brick_slab": "sandstoneRedBrickSlab",
    "minecraft:nether_portal": "voidBlock",
    "minecraft:bone_block": "boneBlock",
    "minecraft:chain": "ironBlock",
    "minecraft:hopper": "ironBlock",
    "minecraft:lodestone": "stoneSmooth",

    # ── polished / extra stone variants ───────────────────────────────────
    "minecraft:polished_andesite": "andesiteSmooth",
    "minecraft:polished_andesite_stairs": "andesiteStair",
    "minecraft:polished_andesite_slab": "andesiteSlab",
    "minecraft:andesite_stairs": "andesiteStair",
    "minecraft:andesite_slab": "andesiteSlab",
    "minecraft:polished_granite": "graniteSmooth",
    "minecraft:polished_granite_stairs": "graniteStair",
    "minecraft:polished_granite_slab": "graniteSlab",
    "minecraft:granite_stairs": "graniteStair",
    "minecraft:granite_slab": "graniteSlab",
    "minecraft:polished_diorite": "dioriteSmooth",
    "minecraft:polished_diorite_stairs": "dioriteStair",
    "minecraft:polished_diorite_slab": "dioriteSlab",
    "minecraft:diorite_stairs": "dioriteStair",
    "minecraft:diorite_slab": "dioriteSlab",
    "minecraft:stone_brick_slab": "stoneBrickSlab",
    "minecraft:stone_brick_stairs": "stairStoneBrick",
    "minecraft:stone_brick_wall": "stoneBrick",
    "minecraft:mossy_stone_bricks": "stoneBrickMossy",
    "minecraft:mossy_stone_brick_slab": "stoneBrickSlab",
    "minecraft:mossy_stone_brick_stairs": "stairStoneBrick",
    "minecraft:infested_mossy_stone_bricks": "stoneBrickMossy",
    "minecraft:infested_stone_bricks": "stoneBrick",
    "minecraft:chiseled_stone_bricks": "stoneCarved",
    "minecraft:cracked_stone_bricks": "stoneBrick",
    "minecraft:cobblestone_stairs": "cobblestoneStair",
    "minecraft:cobblestone_slab": "cobblestoneSlab",
    "minecraft:mossy_cobblestone_stairs": "cobblestoneStair",
    "minecraft:mossy_cobblestone_slab": "mossyCobblestoneSlab",
    "minecraft:mossy_cobblestone_wall": "mossyCobblestoneBlock",
    "minecraft:brick_stairs": "stairBrick",
    "minecraft:brick_slab": "brickSlab",
    "minecraft:brick_wall": "brick",
    "minecraft:smooth_quartz_stairs": "stairMarble",
    "minecraft:quartz_stairs": "stairMarble",
    "minecraft:quartz_pillar": "marblePillar",
    "minecraft:chiseled_quartz_block": "marbleCarved",
    "minecraft:cut_sandstone_slab": "sandstoneBrickSlab",
    "minecraft:chiseled_red_sandstone": "sandstoneRedBrick",
    "minecraft:cut_red_sandstone": "sandstoneRedBrick",
    "minecraft:red_sandstone_slab": "sandstoneRedSlab",
    "minecraft:red_sandstone_stairs": "stairSandstoneRed",
    "minecraft:smooth_red_sandstone": "sandstoneSmoothRed",
    "minecraft:smooth_red_sandstone_slab": "sandstoneSmoothRedSlab",
    "minecraft:prismarine": "prismarineBlock",
    "minecraft:prismarine_slab": "prismarineSlab",
    "minecraft:prismarine_stairs": "prismarineStair",
    "minecraft:prismarine_bricks": "prismarineBrick",
    "minecraft:prismarine_brick_slab": "prismarineBrickSlab",
    "minecraft:prismarine_brick_stairs": "prismarineBrickStair",
    "minecraft:dark_prismarine": "prismarineBrick",
    "minecraft:dark_prismarine_slab": "prismarineBrickSlab",
    "minecraft:dark_prismarine_stairs": "prismarineBrickStair",

    # ── remaining wood variants ───────────────────────────────────────────
    "minecraft:jungle_slab": "mapleSlab",
    "minecraft:jungle_stairs": "stairMaple",
    "minecraft:jungle_trapdoor": "mapleSlab",
    "minecraft:jungle_fence": "maplePlank",
    "minecraft:jungle_button": "mapleSlab",
    "minecraft:acacia_slab": "mapleSlab",
    "minecraft:acacia_stairs": "stairMaple",
    "minecraft:acacia_trapdoor": "mapleSlab",
    "minecraft:acacia_fence": "maplePlank",
    "minecraft:acacia_wood": "woodMaple",
    "minecraft:stripped_acacia_wood": "woodMaple",
    "minecraft:stripped_spruce_wood": "woodPine",
    "minecraft:stripped_oak_wood": "wood",
    "minecraft:stripped_birch_wood": "woodBirch",
    "minecraft:stripped_dark_oak_wood": "woodHickory",
    "minecraft:stripped_jungle_wood": "woodMaple",

    # ── remaining glass ───────────────────────────────────────────────────
    "minecraft:gray_stained_glass": "glassBlockBlack",
    "minecraft:light_gray_stained_glass": "glassBlockChrome",
    "minecraft:blue_stained_glass": "glassBlockBlue",
    "minecraft:red_stained_glass": "glassBlockRed",
    "minecraft:green_stained_glass": "glassBlockDarkGreen",
    "minecraft:lime_stained_glass": "glassBlockLightGreen",
    "minecraft:yellow_stained_glass": "glassBlockYellow",
    "minecraft:orange_stained_glass": "glassBlockOrange",
    "minecraft:cyan_stained_glass": "glassBlockCyan",
    "minecraft:light_blue_stained_glass": "glassBlockCyan",
    "minecraft:pink_stained_glass": "glassBlockPink",
    "minecraft:purple_stained_glass": "glassBlockPurple",
    "minecraft:magenta_stained_glass": "glassBlockPink",
    "minecraft:brown_stained_glass": "glassBlockOrange",
    "minecraft:tinted_glass": "glassBlockBlack",
    "minecraft:blackstone_slab": "basaltSlab",
    "minecraft:blackstone_stairs": "basaltStair",
    "minecraft:nether_brick_wall": "basaltBrick",
    "minecraft:redstone_torch": "ledLight",
    "minecraft:soul_torch": "ledLight",
    "minecraft:soul_wall_torch": "ledLight",
    "minecraft:redstone_wall_torch": "ledLight",
    "minecraft:ochre_froglight": "ledLight",
    "minecraft:verdant_froglight": "ledLight",
    "minecraft:pearlescent_froglight": "ledLight",
    "minecraft:shroomlight": "ledLight",
    "minecraft:deepslate": "slateBlock",
    "minecraft:polished_deepslate": "slateSmooth",
    "minecraft:deepslate_bricks": "slateBrick",
    "minecraft:deepslate_tiles": "slateTiles",
    "minecraft:chiseled_deepslate": "slateCarved",
    "minecraft:cobbled_deepslate": "slateBlock",
    "minecraft:calcite": "marbleBlock",
    "minecraft:tuff": "andesite",
    "minecraft:dripstone_block": "sandstoneSmooth",
    "minecraft:moss_block": "mossyBlock",
    "minecraft:rooted_dirt": "mudBlock",
    "minecraft:amethyst_block": "amethystBlock",
    "minecraft:copper_block": "copperBlock",
    "minecraft:oxidized_copper": "prismarineBlock",
    "minecraft:mud_bricks": "mudBlock",
    "minecraft:packed_mud": "mudBlock",

    # Natural stones. world_to_islands strips these via BULK before it gets
    # here; a schematic keeps them, because there they are deliberate.
    "minecraft:stone": "stone",
    "minecraft:andesite": "andesite",
    "minecraft:diorite": "diorite",
    "minecraft:granite": "granite",
    "minecraft:dirt": "mudBlock",
    "minecraft:gravel": "cobblestoneBlock",
    "minecraft:sand": "sand",
    "minecraft:red_sand": "sandstoneRed",
    "minecraft:clay": "clay",
    "minecraft:obsidian": "voidStoneBlock",
    "minecraft:crying_obsidian": "voidStonePolished",
    "minecraft:ice": "ice",
    "minecraft:packed_ice": "iceCompact",
    "minecraft:blue_ice": "iceCompact",
    "minecraft:snow_block": "snowCompact",
    "minecraft:water": "glassBlockBlue",
    "minecraft:coal_ore": "coalBlock",
    "minecraft:iron_ore": "ironBlock",
    "minecraft:gold_ore": "goldBlock",
    "minecraft:diamond_ore": "diamondBlock",
    "minecraft:emerald_ore": "amethystBlock",
    "minecraft:redstone_ore": "redBlock",
    "minecraft:lapis_ore": "blueBlock",

    # 1.17+ odds and ends
    "minecraft:quartz_bricks": "marbleBrick",
    "minecraft:quartz_slab": "marbleSlab",
    "minecraft:azalea_leaves": "leavesBlock",
    "minecraft:flowering_azalea_leaves": "leavesBlock",
    "minecraft:azalea": "leavesBlock",
    "minecraft:flowering_azalea": "leavesBlock",
    "minecraft:mangrove_leaves": "leavesBlock",
    "minecraft:mangrove_planks": "cherryBlossomPlank",
    "minecraft:mangrove_log": "woodCherryBlossom",
    "minecraft:cherry_leaves": "leavesBlock",
    "minecraft:cherry_planks": "cherryBlossomPlank",
    "minecraft:cherry_log": "woodCherryBlossom",
    "minecraft:bamboo_planks": "bambooBlock",
    "minecraft:bamboo_block": "bambooBlock",
    "minecraft:moss_carpet": "mossySlab",
    "minecraft:big_dripleaf": "leavesBlock",
    "minecraft:glow_lichen": "mossyBlock",
    "minecraft:sculk": "voidBlock",
    "minecraft:sculk_catalyst": "voidStoneCarved",
}

# Small decorations with no sensible block equivalent: dropped rather than
# turned into a full cube that would look wrong.
DROP = {
    "minecraft:grass", "minecraft:tall_grass", "minecraft:fern", "minecraft:large_fern",
    "minecraft:dandelion", "minecraft:poppy", "minecraft:blue_orchid", "minecraft:allium",
    "minecraft:azure_bluet", "minecraft:oxeye_daisy", "minecraft:cornflower",
    "minecraft:lily_of_the_valley", "minecraft:sunflower", "minecraft:lilac",
    "minecraft:rose_bush", "minecraft:peony", "minecraft:dead_bush",
    "minecraft:brown_mushroom", "minecraft:red_mushroom", "minecraft:sugar_cane",
    "minecraft:wheat", "minecraft:carrots", "minecraft:potatoes", "minecraft:beetroots",
    "minecraft:sweet_berry_bush", "minecraft:lily_pad", "minecraft:snow",
    "minecraft:oak_sapling", "minecraft:spruce_sapling", "minecraft:birch_sapling",
    "minecraft:rail", "minecraft:redstone_wire", "minecraft:tripwire",
    "minecraft:air", "minecraft:cave_air", "minecraft:void_air",
}


def islands_name(mc):
    if mc in DROP:
        return None
    if mc in MAP:
        return MAP[mc]
    # potted_* -> the pot, so the decoration still reads as an object
    if mc.startswith("minecraft:potted_"):
        return "clayOrange"
    return None


